title: "びるすぴ"
description: "GitHub PagesでJekyllを使ったブログ"
theme: minima
baseurl: "/birusupi" # サブディレクトリを設定
url: "https://spira-unplugged.github.io" # ベースURL（末尾のスラッシュなし）
markdown: kramdown
permalink: /:categories/:year:month:day/:slug/